name: Deploy Heroku

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY_HOST: ${{ secrets.DOCKER_REGISTRY_HOST }}
  DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
  DOCKER_REGISTRY_TOKEN: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
  DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - name: Set env HEROKU_APP
        run: |
          echo "HEROKU_APP=energy-client" >> $GITHUB_ENV

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_REGISTRY_USERNAME }}
          password: ${{ env.DOCKER_REGISTRY_TOKEN }}

      - name: Create Env
        run: |
          touch .env
          echo DOCKER_REGISTRY=${{ env.DOCKER_REGISTRY_HOST }} >> .env
          echo DOCKER_IMAGE=${{ env.DOCKER_IMAGE }} >> .env
          echo VERSION=latest >> .env
          echo FIREBASE_API_KEY=${{secrets.FIREBASE_API_KEY}} >> .env
          echo FIREBASE_AUTH_DOMAIN=${{secrets.FIREBASE_AUTH_DOMAIN}} >> .env
          echo FIREBASE_PROJECT_ID=${{secrets.FIREBASE_PROJECT_ID}} >> .env
          echo FIREBASE_STORAGE_BUCKET=${{secrets.FIREBASE_STORAGE_BUCKET}} >> .env
          echo FIREBASE_MESSAGING_SENDER_ID=${{secrets.FIREBASE_MESSAGING_SENDER_ID}} >> .env
          echo FIREBASE_APP_ID=${{secrets.FIREBASE_APP_ID}} >> .env
          echo FIREBASE_MEASUREMENT_ID=${{secrets.FIREBASE_MEASUREMENT_ID}} >> .env
          echo FIREBASE_DATABASE_URL=${{secrets.FIREBASE_DATABASE_URL}} >> .env

      - name: Build Docker Image
        run: docker compose build

      - name: Push Docker Image
        run: docker compose push web

      - name: Login to Heroku
        run: heroku container:login

      - name: Push Images to Heroku
        run: heroku container:push web --arg DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST,DOCKER_IMAGE=$DOCKER_IMAGE,BRANCH_TAG=$BRANCH_TAG

      - name: Release
        run: heroku container:release web
