name: Test

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

  test-ui:
    name: Test UI
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome106-ff106
      options: --user 1001

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn

      - name: Create Environment
        run: |
          touch .env
          echo NEXT_PUBLIC_REACT_BASE_API_URL=http://localhost:3001/api/v1 >> .env

      - name: Cypress Test
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          build: yarn build
          start: |
            yarn start
          command: yarn cypress:run
